font_size: 20
font_bold: true
font: arial

color_red: 240
color_green: 240
color_blue: 240

image_s:
  type: aimg
  value: textures/interface/MenuPauseButton.png
image_h:
  type: aimg
  value: textures/interface/MenuPauseButtonH.png
