font_size: 18
font_bold: true
font: arial

color_red: 240
color_green: 240
color_blue: 240

image_s:
  type: aimg
  value: textures/interface/MenuDefenseButton.png
image_h:
  type: aimg
  value: textures/interface/MenuDefenseButtonD.png
image_d:
  type: aimg
  value: textures/interface/MenuDefenseButtonH.png
